name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:

  build:

    runs-on: ubuntu-22.04
    environment: Prod
    steps:

    #- uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: logistikmaster
          password: ${{ secrets.DOCKERHUB_USERNAME }}
    - name: Cat passw
      run: cat ${{ secrets.DOCKERHUB_USERNAME }}
    
      
